# Generated by Django 5.0 on 2023-12-16 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pan', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('normalize', models.BooleanField()),
                ('reverse', models.BooleanField()),
                ('trim', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FilterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(max_length=50)),
                ('frequency', models.FloatField()),
                ('is_on', models.BooleanField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renderer.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bpm', models.IntegerField()),
                ('swing', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bars', models.IntegerField()),
                ('position', models.IntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renderer.song')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renderer.song'),
        ),
        migrations.CreateModel(
            name='StepSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.JSONField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renderer.channel')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renderer.pattern')),
            ],
        ),
    ]
