# Generated by Django 5.0 on 2023-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0004_remove_sample_normalize_remove_sample_reverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
