# Generated by Django 5.0 on 2023-12-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('renderer', '0006_load_samples'),
    # ]

    dependencies = [
        ('renderer', '0005_song_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
