# Generated by Django 5.0 on 2023-12-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0007_step_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='waveform',
            field=models.ImageField(null=True, upload_to='waveforms'),
        ),
        migrations.AddField(
            model_name='track',
            name='normalizeSample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='pitchShift',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='rootPitch',
            field=models.CharField(default='C3', max_length=5),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='renderer.song'),
        ),
        migrations.AlterField(
            model_name='step',
            name='pitch',
            field=models.CharField(default='C3', max_length=5),
        ),
    ]
