# Generated by Django 5.0 on 2023-12-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0008_sample_waveform_track_normalizesample_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='normalizeSample',
            new_name='normalize',
        ),
        migrations.AddField(
            model_name='track',
            name='endOffset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='fadeIn',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='fadeOut',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='startOffset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='trim',
            field=models.BooleanField(default=False),
        ),
    ]
