# Generated by Django 5.0 on 2024-01-07 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0009_rename_normalizesample_track_normalize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='filter',
        ),
        migrations.AddField(
            model_name='filter',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='renderer.step'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='renderer.track'),
        ),
    ]
