# Generated by Django 5.0 on 2024-01-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0011_song_lastedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
