# Generated by Django 5.0 on 2024-01-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0012_step_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
