# Generated by Django 5.0 on 2024-01-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0014_piano_sample_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='isPiano',
            field=models.BooleanField(default=False),
        ),
    ]
