# Generated by Django 5.0 on 2024-01-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0016_remove_track_ispiano_pattern_pianoindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='retrigger',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
