# Generated by Django 5.0 on 2024-01-24 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0020_sample_frames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pan', models.FloatField(default=0)),
                ('volume', models.FloatField(default=-6)),
                ('transpose', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=1)),
                ('rootPitch', models.CharField(default='C3', max_length=5)),
                ('pitchShift', models.IntegerField(default=0)),
                ('reverse', models.BooleanField(default=False)),
                ('normalize', models.BooleanField(default=False)),
                ('trim', models.BooleanField(default=False)),
                ('fadeIn', models.PositiveSmallIntegerField(default=0)),
                ('fadeOut', models.PositiveSmallIntegerField(default=0)),
                ('startOffset', models.PositiveIntegerField(default=0)),
                ('endOffset', models.PositiveIntegerField(default=0)),
                ('playMode', models.CharField(default='oneshot', max_length=8)),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='renderer.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='patch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='renderer.patch'),
        ),
    ]
