# Generated by Django 5.0 on 2024-01-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0021_patch_filter_patch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='q',
        ),
        migrations.AddField(
            model_name='filter',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
